//! # ESP-IDF Umbrella Module (`esp_idf`)
//!
//! **What:** The single, top-level import that re-exports every wrapped ESP-IDF subsystem
//! (GPIO, I2C, SPI, Wi-Fi, RTOS, LVGL, MQTT, etc.) as Zig-friendly namespaces.
//!
//! **What it does:** Acts as a facade: it lazy-imports each subsystem module once and
//! applies compile-time guards so that optional components (led_strip, esp-dsp) and
//! target-incompatible features (Wi-Fi on ESP32-H2) produce clear `@compileError`
//! messages instead of linker errors.
//!
//! **How:** Each `pub const` field imports its corresponding file from `imports/`.
//! Conditional fields use `switch` on C header defines (`HAS_ESP_DSP`,
//! `HAS_ESP_LED_STRIP`) or the compile-time `currentTarget` enum derived from
//! `CONFIG_IDF_TARGET` in `sys` (the raw C binding module).
//!
//! **When to use:** Always.  Import this module as the canonical gateway to all
//! peripherals and services.  Never import individual subsystem files directly —
//! they rely on module names set up by `build.zig`.
//!
//! **What it takes:** No runtime cost — all wiring is resolved at compile time.
//!
//! **Example:**
//! ```zig
//! const idf = @import("esp_idf");
//!
//! pub fn app_main() void {
//!     // GPIO
//!     try idf.gpio.config(&my_cfg);
//!     // RTOS
//!     idf.rtos.Task.delayMs(500);
//!     // Logging
//!     idf.log.ESP_LOG(alloc, idf.log.default_level, "TAG", "Hello {s}\n", .{"world"});
//! }
//! ```

/// Bootloader & eFuse register bindings.
pub const bl = @import("bootloader");
/// Bluetooth radio power-domain control.
pub const bt = @import("bluetooth");
/// CRC checksum helpers (ROM hardware + Zig `std.hash`).
pub const crc = @import("crc");
/// ESP-DSP signal-processing library (requires `espressif/esp-dsp` component).
pub const dsp = switch (sys.HAS_ESP_DSP != 0) {
    true => @import("dsp"),
    false => @compileError("requires: idf.py add-component espressif/esp-dsp"),
};
/// Bidirectional bridge between C `esp_err_t` and Zig error unions.
pub const err = @import("error");
/// GPIO configuration, interrupt, level, and drive-cap control.
pub const gpio = @import("gpio");
/// Heap allocators (`HeapCapsAllocator`, `MultiHeapAllocator`, `VPortAllocator`) and heap-trace.
pub const heap = @import("heap");
/// HTTP server (httpd) and client (`esp_http_client`) wrappers.
pub const http = @import("http");
/// I²C master bus and device management (v5.x driver API).
pub const i2c = @import("i2c");
/// I²S channel driver for PDM/TDM/standard audio streaming.
pub const i2s = @import("i2s");
/// LVGL graphics library + `esp_lvgl_port` integration.
pub const lvgl = @import("lvgl");
/// Addressable LED strip driver (requires `espressif/led_strip` component).
pub const led = switch (sys.HAS_ESP_LED_STRIP != 0) {
    true => @import("led"),
    false => @compileError("requires: idf.py add-component espressif/led_strip"),
};
/// Logging backend routing `std.log` through `esp_log_write()`.
pub const log = @import("log");
/// lwIP TCP/IP stack bindings (sockets, netif, DNS, etc.).
pub const lwip = @import("lwip");
/// MQTT client and transport-layer bindings.
pub const mqtt = @import("mqtt");
// pub const esp_now = @import("now");
/// PHY / RF test-mode helpers (Wi-Fi, BLE, BT tone TX/RX).
pub const phy = @import("phy");
/// Pulse Counter (PCNT) hardware peripheral wrapper.
pub const pulse = @import("pulse");
/// Zig panic handler that prints to ESP-IDF console and halts.
pub const esp_panic = @import("panic");
/// FreeRTOS primitives: Task, Queue, Semaphore, Timer, EventGroup, etc.
pub const rtos = @import("rtos");
/// SEGGER Real-Time Transfer (RTT) debug I/O.
pub const segger = @import("segger");
/// SPI master bus/device management and SD-over-SPI host.
pub const spi = @import("spi");
/// UART driver: install, configure, read/write, pattern detection.
pub const uart = @import("uart");
/// IDF firmware version parser.
pub const ver = @import("ver");
/// Wi-Fi driver (STA, AP, scan, ESP-NOW, enterprise). Not available on Wi-Fi-less targets.
pub const wifi = switch (currentTarget) {
    .esp32h2, .esp32h21, .esp32h4, .esp32p4 => @compileError("Wifi unsupported!"),
    else => @import("wifi"),
};
/// Raw C binding module generated by `build.zig` from ESP-IDF headers.
pub const sys = @import("sys");

/// Enumeration of supported ESP32 SoC targets, derived from `CONFIG_IDF_TARGET`.
const Device = enum {
    esp32,
    esp32s2,
    esp32s3,
    esp32c2,
    esp32c3,
    esp32c5,
    esp32c6,
    esp32c61,
    esp32h2,
    esp32h21,
    esp32h4,
    esp32p4,
};

/// The active SoC target resolved at compile time from `CONFIG_IDF_TARGET`.
pub const currentTarget = blk: {
    const target_str = sys.CONFIG_IDF_TARGET;
    break :blk @import("std").meta.stringToEnum(Device, target_str) orelse {
        @compileError("Unknown ESP32 device target: " ++ target_str);
    };
};

// Check all imports
comptime {
    _ = sys;
    _ = bl;
    _ = bt;
    _ = crc;
    _ = err;
    _ = gpio;
    _ = heap;
    _ = http;
    _ = i2c;
    _ = i2s;
    _ = lvgl;
    _ = log;
    _ = lwip;
    _ = mqtt;
    // _ = esp_now;
    _ = phy;
    _ = pulse;
    _ = esp_panic;
    _ = rtos;
    _ = segger;
    _ = spi;
    _ = uart;
    _ = ver;
    _ = switch (currentTarget) {
        .esp32h2, .esp32h21, .esp32h4, .esp32p4 => {},
        else => wifi,
    };
    if (sys.HAS_ESP_DSP != 0) _ = dsp;
    if (sys.HAS_LED_STRIP != 0) _ = led;
}
